cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'direnv'
brew 'npm'
brew 'pipx'
brew 'pyenv'
brew 'rbenv'
brew 'starship'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask 'alfred'
cask 'anythingllm'
cask 'arq'
cask 'audio-hijack'
cask 'blackhole-2ch'
cask 'dropbox'
cask 'focus'
cask 'font-hack-nerd-font'
cask 'hazel'
cask 'iterm2'
cask 'obsidian'
cask 'plex'
cask 'popclip'
cask 'rectangle-pro'
cask 'typinator'
cask 'visual-studio-code'
cask 'whatsapp'